[package]
name = "endlesshashes"
version = "1.0.0"
edition = "2021"

[profile.release]
incremental = true
opt-level = 3
strip = "debuginfo"
lto = true

[dependencies]
blake3 = "1.5.4"
getrandom = "0.2.15"
hex = "0.4.3"
