[package]
name = "endlesshashes"
version = "1.0.0"
edition = "2021"

[profile.release]
incremental = true
opt-level = 3
strip = "debuginfo"
lto = true

[dependencies]
getrandom = "0.2.15"
hex = "0.4.3"
sha3 = "0.10.8"
